global using System.Text;
global using Domain.Entities;
global using Domain.Enums;
global using Domain.Interfaces;
global using Application.Services;
global using Application.Dtos;
global using Infrastructure.Data;
global using Infrastructure.Repositories;
global using ConsoleApp.Menus;
