public abstract class User
{
    private int Id { get; set; }
    private string userName { get; set; }
    private UserRole Role { get; set; }
    private string Password { get; set; }

    public User(string userName, UserRole Role, string Password)
    {
        // This is just a placeholder. In a real application, the ID would be generated by the database.
        Id = new Random().Next(1, 1000); 
        this.userName = userName;
        this.Role = Role;
        this.Password = Password;
    }
}